server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/orders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  flyway:
    validate-migration-naming: true

  jpa:
    hibernate:
      ddl-auto: validate