server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:orders-worker}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.tec.itlabs.orders.worker.dto"
        spring.json.value.default.type: "br.tec.itlabs.orders.worker.dto.OrderCreatedEvent"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/orders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  flyway:
    validate-migration-naming: true

  jpa:
    hibernate:
      ddl-auto: validate

app:
  kafka:
    topics:
      order-created: orders.created