spring:
  application:
    name: Orders-Worker

  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL8Dialect é desnecessário e está deprecated; deixe o Hibernate escolher.
        # dialect: org.hibernate.dialect.MySQL8Dialect
        # (se quiser forçar, use org.hibernate.dialect.MySQLDialect)
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    validate-migration-naming: true

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: orders-worker
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "br.tec.itlabs.orders.worker.dto"
        spring.json.value.default.type: "br.tec.itlabs.orders.worker.dto.OrderCreatedEvent"

    listener:
      ack-mode: manual

server:
  port: 8081

app:
  kafka:
    topics:
      order-created: orders.created

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
